<<<<<<< HEAD:src/FirstForRentals.Web/Application.aspx.designer.cs
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstForRentals.Web
{


    public partial class Application
    {
    }
}
=======
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstForRentals.Web
{


    public partial class Application
    {
    }
}
>>>>>>> origin/master:src/FirstForRentals.Web/Application.aspx.designer.cs
